<?php //006fc
// This Software is the property of D³ Data Development and is protected by copyright law - it is NOT Freeware.  Any unauthorized use of this software without a valid license key is a violation of the license agreement and will be prosecuted by civil and criminal law.  Inhaber: Thomas Dartsch Alle Rechte vorbehalten  @package Bestellbestaetigung_drucken @version 4.0.1.1 PHP56 (10.01.2019) @author  Markus Gärtner support@shopmodule.com @copyright (C) 2019, D3 Data Development @see http://www.shopmodule.com
if(!extension_loaded('ionCube Loader')){$__oc=strtolower(substr(php_uname(),0,3));$__ln='ioncube_loader_'.$__oc.'_'.substr(phpversion(),0,3).(($__oc=='win')?'.dll':'.so');if(function_exists('dl')){@dl($__ln);}if(function_exists('_il_exec')){return _il_exec();}$__ln='/ioncube/'.$__ln;$__oid=$__id=realpath(ini_get('extension_dir'));$__here=dirname(__FILE__);if(strlen($__id)>1&&$__id[1]==':'){$__id=str_replace('\\','/',substr($__id,2));$__here=str_replace('\\','/',substr($__here,2));}$__rd=str_repeat('/..',substr_count($__id,'/')).$__here.'/';$__i=strlen($__rd);while($__i--){if($__rd[$__i]=='/'){$__lp=substr($__rd,0,$__i).$__ln;if(file_exists($__oid.$__lp)){$__ln=$__lp;break;}}}if(function_exists('dl')){@dl($__ln);}}else{die('The file '.__FILE__." is corrupted.\n");}if(function_exists('_il_exec')){return _il_exec();}echo("Site error: the ".(php_sapi_name()=='cli'?'ionCube':'<a href="http://www.ioncube.com">ionCube</a>')." PHP Loader needs to be installed. This is a widely used PHP extension for running ionCube protected PHP code, website security and malware blocking.\n\nPlease visit ".(php_sapi_name()=='cli'?'get-loader.ioncube.com':'<a href="http://get-loader.ioncube.com">get-loader.ioncube.com</a>')." for install assistance.\n\n");exit(199);
?>
HR+cPs4MJUvO+RN19QNOpOSnOSVDcGKlVs55fuIub3M61zlQc6EpO4A770Qjwk1iCE33YCFCED8E
NRp5ejE/YhUNImMHXw2ZY/MPfGFIqjgTLoeIIcFDeuSVDfOOvNkL6glGU9t23LVMDjkd6bt24XVF
5vT2PYMlar9hSfli2awwzBw5XVjmWNVwksiZKUan3vjKjDoqS0cODcmuRrSuDg+usECTuRv0sQYa
86KIIpw3X0JRW22DCJK/tP0wbxw+9b4gApsTeUQucmnmB8ZXar61VdW1621d1H7YibQX/kb75ssb
6VDH/nLzsFtxDVHszeLJ1NNnHU69dje5zKnMhiEVeqxGZqH8W449Jaxtt2KlweRqddEe8Vm1c6tE
Bb2WFqiW2Bco9g71GOhQxrlHJ9sR3mQP9XOJyipQwgTVXaDweA3xhlnAtkPQXCjodXbc5T0kEtrE
VgLJWwBD4SEm5u3ITic76hg+oGaFPmaty7fKWGzWAwbdI+xD4aDeKmw0qCLBFoLW5QuOkszHk60q
hm2FBT5Iqoh7MQl/C+O5eYQngLNXamnjLBd77bdKLzrR1eZyBBdVAv4UJGnf+ecvZOnjXmR1r8uS
DICLCH6AFskVY5WbsFj5XPkfdbbgjFm7SG4G7Ox3K5rmTHLodLxQXj8LRO9hKoAUhIFEWaVm0fwk
pCnl8URi60y52NbK2m3gpMO36Vj/neXzKWNKbBBwI+yg4Z4HzI3viQ4D9GOngylxLKj+pb017EZA
z2dsXe+0LzsO6MbgrtujOXVCbY5L1EpSb7EiTBIjfPs+QHSLyVVoOBYlcerP2zw7rYbEDRZY502S
yedD6bPRZQXf4cpWxUsBZNC/NiYEgPPo+w+jREdnbpL41o3o2WMejucshDWrxOFELeQw9b2OrrT6
+QrBKywSgfMwhCjeseD5t5F/7O30ffl0LDTnaGvoeYRj6vgTSn+yQnVdDHLFB8tkGo1UkrLcKwm4
xOAk5FXtE30schAUJ6iJolwvmBhW78+bH0sXL8oIC2kp4FeaBHIse6Cl/dRhtdc+MmGvy1YuUAyq
moW0h6tsj/bi9UX+HOULZOho7cOYp2naNnvt+A6HHZdColePwTryHr1aoX/BLyB8OaIGAIggB51f
iwsD58ECleoOBvEOZmpWvNpmQmGv1LHB1ENbfMnENVCz0Ws0TAJnoMxoCUddf2qxl7QQhvqI6dJx
ajbByGAM6cStr2HWt+oS1ij9vCvUzZPlWZ1ZTMLZWTxySOpdmy+BffyIAmV1EHQJ4EaCw4gvdETD
9YMSbH9X+MWZ06DfkqzChYpSRpEfYyC9t6o4m4B166ZfzNlt7isK92QFgHL7/u7k8QUqm90ZsBOz
Ia/IvdiKpLJkjf+4PE2CSufsoVD0QLijrhadC3jWdmgnVHe5QiEd78Q1pVBWbITU+DhbuYtNX/ad
7YafgLg1pVw3GhU3hSgIsargmcORH9GCdNyomqFUeU/E/XnSj/8j9Qj0PX1j2a6A2rsfbGw/zjVx
GtO1TG+9AoBZxsMwna/BeKiwpc03emy4CIwLALvzPwRnn1k3fIampkUtCz2/hl0UDclMDjpG3/mX
cVtkusYR2QXU1jAA9qvGCGKMO+5fuBr2tFNAPcM3iyDBjzs3gnaAeHI3ochpvFTbq/Yu+5fIugnh
Yn62vLPDzGezuTsgK+zOCYOrdkcxSUZjEOexG0ZT8FxUZ9TAiFumOe0G6ri+gxUsbLkrE/NOcxcH
A4ee0IEF9KfLnMvyfjE6/n8Q/GxuEIYshFa7zUFmuJVNlvnp6OwISkIq4C6IlJkkBPSwCIF5kJgX
l+e4TX/FGFxzMvprEL5oO5zrvhZBFxnCmeGAaXficbOPGghwFXTwWeaew60iveJ+rEQFAnsYf5IK
EVbp01c9CcJv9Otmo2oLrQ0sBuhN8oUEjSYPPO0FnFO31EN287NaborqPCKmFKXCVdBTTHpT5H2f
GAkLbkDja22YJBAbV7VSC5GE+cLp0PACWvcvN8uXDduup+6Vij6KMPbKsmMW1/c7r+biPr93mEN9
swHfXlEhXZSQAQ08xd1dStpvFKLN3oI9KfzaTiLoWBhPUk0lUhtbRhn+JY0sFXrP1qEBVlOO1rWd
YZIwiCfovCY4cg+mmxFXGWxtcBqlXriqgnuLoxo9H1ZIqeCwLGGgvVeALVKVZaGSIS7yhlr4WX0F
pjSAHU0V2UNuFXs8cvFXTlKmvmcAQRwvn6iNi2V8Ao2ki2w6h7Too62c9dA9CQ/DTXEV1sugPkSO
tksZtZC2znL8x4+uIQtMgVuwrx3VAk9k9RSZNWvLV+SOVa6u1DkED1VKhgoCbDnObV99P6uSkBrp
zFMWu4CCT7QJoNK/xVXIT+qw/Rdg0oounfHKInN5SBTEaTFFSm/CJXgbtLPFIkhxySYBn1VfnRzp
ZqGjMMFlfREqXO8DRhplw/aEcUZ+zza2tc8VZKwPOHdryu9tA+MJu4zVj5kVfwvLmnQ1kJEzk46q
15y1MK5ZgcBbjaPynsJWbu5hJ5/OgysULH1yBxiYkIZXnWXRSOIBOXJ677cDBCPzjtR2rwv5yyRN
zyvbaI5ZLRRJrxJjClJfLxYASSIWSQOjqKCAnVDPe3cLSt5CLTBUgiHRJ9FqZpPKwgfJ7TWCvmzU
xlR7GA2pGm03k99wlCrZgErMSUEsSNUkUtDRtNFozIKkZXeiPxPxd8ZAx9YTZeur3Ifiq2nb4olI
jwjR23ORFuWtlx/ncz97OCMtaMLHXXJElFieR6Hp9i9nIBic3KbDEvoUexkVN1dpyG35dCT7CyzV
xg2uZWNOA9FymVJxrlFefSSCEX/tlwFEa/4r+Ovag1d9jTyquZcd7ifOQqRuzSpHI4BzfwyPsg7G
qW3l